export enum GameActions {
  battleApproveAction = 'battleApproveAction',
  breakDoorAction = 'breakDoorAction',
  checkBrokenDoorAction = 'checkBrokenDoorAction',
  doorBreakPromtAction = 'doorBreakPromtAction',
  setBattleApproveStateAction = 'setBattleApproveStateAction',
  setBrokenDoorAction = 'setBrokenDoorAction',
  startBattleAction = 'startBattleAction',
  dialDoorAction = 'dialDoorAction',
  dialTreasureAction = 'dialTreasureAction',
  diceThrowAction = 'diceThrowAction',
  moveCardAction = 'moveCardAction',
  checkAllHaveStagingReadyStateAction = 'checkAllHaveStagingReadyStateAction',
  equipItemAction = 'equipItemAction',
  setPlayerReadyStateAction = 'setPlayerReadyStateAction',
  setStagingGameStateAction = 'setStagingGameStateAction',
  approveStagingReadyStateAction = 'approveStagingReadyStateAction',
  startStagingAction = 'startStagingAction',
  unequipItemAction = 'unequipItemAction',
  checkSingleDiceWinnerAction = 'checkSingleDiceWinnerAction',
  selectFirstPlayerAction = 'selectFirstPlayerAction',
  startGameAction = 'startGameAction',
}